#Encoder config -------------------
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

#Battery config -------------------
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y

#Layer LED config -------------------
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=30
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=10
CONFIG_RGBLED_WIDGET_SHOW_LAYER_COLORS=y
CONFIG_RGBLED_WIDGET_LAYER_COLORS="0xFF8C00,0xFF1493,0x00BFFF,0x0040FF,0xFFD700,0xFFFFFF,0x00FFFF,0xFF00FF,0xFF6600,0x9900FF"
